info = input('Digite o que desejar:\n')
print('O tipo primitivo do dado inserido é:', type(info))
print('O dado possui somente espaços?', info.isspace())
print('O dado é um número?', info.isnumeric())
print('O dado é alfabético?', info.isalpha())
print('O dado é alfanumérico?', info.isalnum())
print('O dado está totalmente em maiúsculo?', info.isupper())
print('O dado está totalmente em minúsculo?', info.islower())
print('O dado está capitalizado?', info.istitle())